# -*- coding: utf-8 -*-
"""StatusEmoji.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q70eCCEXFMZrI95U_9DOqkr1TTmhSNDl
"""

!pip install keras
!pip install reactionrnn

!wget https://modeldepot.io/assets/uploads/models/models/e76620d2-41b0-4876-a4ba-d51388fe3444_reactionrnn_weights.hdf5

reaction_weights='e76620d2-41b0-4876-a4ba-d51388fe3444_reactionrnn_weights.hdf5'

from reactionrnn import reactionrnn

react = reactionrnn(reaction_weights)
react.predict("Ronaldo is a GOAT ")